from pathlib import Path

p=Path('index.html')
html=p.read_text(encoding='utf-8')
if 'id="draftCoach"' in html:
    print('Draft Coach already injected')
    raise SystemExit

coach_css='''<style>
.coach-wrap{margin-top:28px;padding:24px;border:1px solid #283753;border-radius:24px;background:linear-gradient(145deg,#0b1322,#11172a)}
.coach-head{display:flex;justify-content:space-between;gap:18px;align-items:end;flex-wrap:wrap}.coach-head h3{font-size:28px;margin:5px 0}.coach-head p{margin:0;color:#8f9db8;max-width:680px;line-height:1.6}.coach-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:20px}.coach-panel{border:1px solid #22304b;background:#0a101c;border-radius:18px;padding:18px}.coach-panel h4{margin:0 0 12px;font-size:16px}.coach-picks{display:grid;gap:8px}.coach-row{display:flex;gap:8px;align-items:center}.coach-row select{flex:1;background:#0d1626;border:1px solid #2b3a58;color:#eef4ff;border-radius:11px;padding:10px}.coach-clear{border:1px solid #33435f;background:#121b2d;color:#b7c3d8;border-radius:10px;padding:9px 11px;cursor:pointer}.coach-score{display:grid;grid-template-columns:130px 1fr;gap:18px;align-items:center;margin-top:18px}.score-ring{width:118px;height:118px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(#46e6ff var(--score,0%),#1b2942 0);position:relative}.score-ring:after{content:'';position:absolute;inset:11px;border-radius:50%;background:#0b1220}.score-ring strong{position:relative;z-index:1;font-size:28px}.coach-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.coach-metric{padding:10px;border:1px solid #23314c;border-radius:12px;background:#080d17}.coach-metric b{display:block;font-size:13px}.coach-metric span{font-size:9px;color:#7f8da7}.coach-alerts{margin-top:14px;display:grid;gap:8px}.coach-alert{padding:11px 12px;border-radius:12px;border:1px solid #2a3956;color:#b9c6db;background:#0b1321;font-size:13px}.coach-alert.good{border-color:#2c7559;color:#9cf0c3}.coach-alert.warn{border-color:#735b2e;color:#ffd98a}.coach-recs{margin-top:16px}.coach-chip{display:inline-flex;margin:5px 5px 0 0;padding:8px 10px;border:1px solid #2e3d5b;border-radius:999px;color:#cbd7eb;background:#10192a;font-size:12px}.coach-note{margin-top:14px;color:#71809b;font-size:11px;line-height:1.5}@media(max-width:760px){.coach-grid,.coach-score{grid-template-columns:1fr}.coach-metrics{grid-template-columns:1fr 1fr}.score-ring{margin:auto}}
</style>'''
html=html.replace('</head>',coach_css+'</head>')

coach_markup='''<div id="draftCoach" class="coach-wrap"><div class="coach-head"><div><small>DRAFT COACH BETA</small><h3>Construye tu 5v5</h3><p>Selecciona aliados y rivales. El coach revisa estructura, balance de daño y herramientas de equipo. No predice quién ganará: señala fortalezas, huecos y picks a considerar.</p></div><button class="secondary" id="coachReset" type="button">Limpiar draft</button></div><div class="coach-grid"><section class="coach-panel"><h4>Tu equipo</h4><div id="allyPicks" class="coach-picks"></div></section><section class="coach-panel"><h4>Rivales</h4><div id="enemyPicks" class="coach-picks"></div></section></div><div class="coach-score"><div class="score-ring" id="scoreRing"><strong id="coachScore">0</strong></div><div><div class="coach-metrics" id="coachMetrics"></div><div class="coach-alerts" id="coachAlerts"></div><div class="coach-recs"><b>Recomendaciones editoriales</b><div id="coachRecs"></div></div></div></div><p class="coach-note">El análisis usa etiquetas editoriales del pool actual, no probabilidades de victoria ni datos oficiales de counter.</p></div>'''
needle='<div id="draftGrid" class="draftgrid"></div>'
if needle in html:
    html=html.replace(needle,needle+coach_markup)
else:
    raise RuntimeError('Draft section not found')

coach_js=r'''<script>
(()=>{
const PROFILE={
'Aulus':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:1,wave:1},'Rafaela':{front:0,engage:0,sustain:1,peel:1,phys:0,magic:1,dive:0,wave:0},'Masha':{front:1,engage:1,sustain:1,peel:0,phys:1,magic:0,dive:1,wave:1},'Marcel':{front:0,engage:1,sustain:1,peel:1,phys:0,magic:1,dive:0,wave:0},'Argus':{front:0,engage:0,sustain:1,peel:0,phys:1,magic:0,dive:1,wave:1},'Minotaur':{front:1,engage:1,sustain:1,peel:1,phys:0,magic:1,dive:0,wave:0},'Khufra':{front:1,engage:1,sustain:0,peel:1,phys:0,magic:1,dive:0,wave:0},'Floryn':{front:0,engage:0,sustain:1,peel:1,phys:0,magic:1,dive:0,wave:0},'Gloo':{front:1,engage:1,sustain:1,peel:0,phys:0,magic:1,dive:1,wave:1},'Carmilla':{front:1,engage:1,sustain:1,peel:1,phys:0,magic:1,dive:0,wave:0},'Obsidia':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:0,wave:1},'Hirara':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:1,wave:0},'Estes':{front:0,engage:0,sustain:1,peel:1,phys:0,magic:1,dive:0,wave:0},'Popol & Kupa':{front:0,engage:1,sustain:0,peel:1,phys:1,magic:0,dive:0,wave:1},'Lolita':{front:1,engage:1,sustain:0,peel:1,phys:0,magic:1,dive:0,wave:0},'Valir':{front:0,engage:0,sustain:0,peel:1,phys:0,magic:1,dive:0,wave:1},'Diggie':{front:0,engage:0,sustain:0,peel:1,phys:0,magic:1,dive:0,wave:1},'Bruno':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:0,wave:1},'Lukas':{front:1,engage:1,sustain:1,peel:0,phys:1,magic:0,dive:1,wave:1},'Gord':{front:0,engage:0,sustain:0,peel:0,phys:0,magic:1,dive:0,wave:1},'Edith':{front:1,engage:1,sustain:0,peel:1,phys:0,magic:1,dive:0,wave:1},'Cyclops':{front:0,engage:0,sustain:0,peel:0,phys:0,magic:1,dive:0,wave:1},'Belerick':{front:1,engage:1,sustain:1,peel:1,phys:0,magic:1,dive:0,wave:0},'Ruby':{front:1,engage:1,sustain:1,peel:1,phys:1,magic:0,dive:0,wave:1},'Hanabi':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:0,wave:1},'Eudora':{front:0,engage:1,sustain:0,peel:0,phys:0,magic:1,dive:0,wave:1},'Granger':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:1,wave:1},'Hayabusa':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:1,wave:1},'Nolan':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:1,wave:1},'Tigreal':{front:1,engage:1,sustain:0,peel:1,phys:0,magic:1,dive:0,wave:0},'Xavier':{front:0,engage:0,sustain:0,peel:1,phys:0,magic:1,dive:0,wave:1},'Ixia':{front:0,engage:0,sustain:0,peel:0,phys:1,magic:0,dive:0,wave:1},'Fredrinn':{front:1,engage:1,sustain:1,peel:1,phys:1,magic:0,dive:0,wave:1},'Pharsa':{front:0,engage:0,sustain:0,peel:0,phys:0,magic:1,dive:0,wave:1}}
const ally=document.getElementById('allyPicks'), enemy=document.getElementById('enemyPicks');
const names=DATA.heroes.map(h=>h.name).sort((a,b)=>a.localeCompare(b));
function mkRows(root,prefix){for(let i=0;i<5;i++){const row=document.createElement('div');row.className='coach-row';const s=document.createElement('select');s.id=prefix+i;s.innerHTML='<option value="">Pick '+(i+1)+'</option>'+names.map(n=>`<option>${n}</option>`).join('');s.addEventListener('change',analyze);row.appendChild(s);root.appendChild(row)}}
mkRows(ally,'a');mkRows(enemy,'e');
const get=(p)=>[0,1,2,3,4].map(i=>document.getElementById(p+i).value).filter(Boolean);
function sum(team,key){return team.reduce((t,n)=>t+(PROFILE[n]?.[key]||0),0)}
function uniqueRoles(team){return new Set(team.map(n=>DATA.heroes.find(h=>h.name===n)?.lane).filter(Boolean)).size}
function recommend(allies,enemies){const pool=DATA.heroes.filter(h=>!allies.includes(h.name)&&!enemies.includes(h.name));const scored=pool.map(h=>{let s=0,p=PROFILE[h.name]||{};if(sum(allies,'front')<1)s+=3*(p.front||0);if(sum(allies,'engage')<1)s+=3*(p.engage||0);if(sum(allies,'peel')<1)s+=2*(p.peel||0);if(sum(allies,'magic')<1)s+=2*(p.magic||0);if(sum(allies,'phys')<1)s+=2*(p.phys||0);if(enemies.some(n=>['Hayabusa','Nolan','Hirara','Masha'].includes(n)))s+=2*(p.peel||0)+2*(h.name==='Khufra');if(enemies.some(n=>['Estes','Rafaela','Floryn'].includes(n)))s+=h.name==='Valir'?2:0;return [h.name,s]}).sort((a,b)=>b[1]-a[1]);return scored.filter(x=>x[1]>0).slice(0,5)}
function analyze(){const A=get('a'),E=get('e');const dup=[...A,...E].filter((n,i,arr)=>arr.indexOf(n)!==i);const metrics=[['Frontline',sum(A,'front')],['Engage',sum(A,'engage')],['Peel',sum(A,'peel')],['Sustain',sum(A,'sustain')],['Daño físico',sum(A,'phys')],['Daño mágico',sum(A,'magic')],['Wave clear',sum(A,'wave')],['Roles',uniqueRoles(A)]];document.getElementById('coachMetrics').innerHTML=metrics.map(([n,v])=>`<div class="coach-metric"><b>${v}</b><span>${n.toUpperCase()}</span></div>`).join('');let score=0;if(A.length===5)score+=20;score+=Math.min(sum(A,'front'),1)*12+Math.min(sum(A,'engage'),1)*12+Math.min(sum(A,'peel'),1)*10+Math.min(sum(A,'sustain'),1)*8+Math.min(sum(A,'phys'),1)*10+Math.min(sum(A,'magic'),1)*10+Math.min(sum(A,'wave'),2)*5+Math.min(uniqueRoles(A),5)*2;if(dup.length)score-=15;score=Math.max(0,Math.min(100,score));document.getElementById('coachScore').textContent=score;document.getElementById('scoreRing').style.setProperty('--score',score+'%');const alerts=[];if(A.length<5)alerts.push(['warn',`Completa los ${5-A.length} pick(s) aliado(s) restantes.`]);if(sum(A,'front')<1)alerts.push(['warn','Falta frontline: tu backline puede quedarse sin espacio.']);if(sum(A,'engage')<1)alerts.push(['warn','Falta engage claro: puede costar iniciar peleas favorables.']);if(sum(A,'peel')<1&&E.some(n=>PROFILE[n]?.dive))alerts.push(['warn','El rival tiene dive y tu equipo casi no tiene peel.']);if(sum(A,'magic')<1)alerts.push(['warn','Daño demasiado físico: el rival puede itemizar armadura con facilidad.']);if(sum(A,'phys')<1)alerts.push(['warn','Daño demasiado mágico: falta una amenaza física consistente.']);if(uniqueRoles(A)<Math.min(A.length,4))alerts.push(['warn','Hay mucha repetición de roles. Revisa cobertura de líneas.']);if(dup.length)alerts.push(['warn','Hay picks repetidos entre ambos equipos.']);if(A.length===5&&alerts.length===0)alerts.push(['good','Composición estructuralmente equilibrada. Ahora importan ejecución, matchup y macro.']);document.getElementById('coachAlerts').innerHTML=alerts.map(x=>`<div class="coach-alert ${x[0]}">${x[1]}</div>`).join('');const recs=recommend(A,E);document.getElementById('coachRecs').innerHTML=recs.length?recs.map(([n])=>`<span class="coach-chip">${n}</span>`).join(''):'<span class="coach-chip">Añade picks para recibir sugerencias</span>'}
document.getElementById('coachReset').onclick=()=>{document.querySelectorAll('#draftCoach select').forEach(s=>s.value='');analyze()};analyze();
})();
</script>'''
html=html.replace('</body>',coach_js+'</body>')
p.write_text(html,encoding='utf-8')
print('Injected Draft Coach')
